export enum REGIONS {
    PETITES_ILES = 'PETITES_ILES',
    GRANDES_ILES = 'GRANDES_ILES',
    FORETS = 'FORETS',
    DESERT = 'DESERT',
    TERRE_SAUVAGE = 'TERRE_SAUVAGE',
    MONTAGNE = 'MONTAGNE'
}
